language: python
python:
- '2.7'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libplot-dev plotutils

install: 'git clone https://github.com/biggles-plot/biggles && cd biggles && python setup.py install && cd .. && rm -rf biggles'

script: python render_website.py

notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  github_token: $GITHUB_TOKEN
  on:
    branch: master
